name: dubsoft
markdown: redcarpet
gems: [jekyll_image_encode, jekyll-press]
exclude: [README.md, vector, Gemfile, Gemfile.lock]
permalink: pretty
assets:
  js_compressor:  uglifier
  css_compressor: sass
sass:
  sass_dir: _includes/
  style: compressed

