name: dubsoft
markdown: redcarpet
gems: [jekyll_image_encode, jekyll-minify-html]
exclude: [README.md, vector, Gemfile, Gemfile.lock]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: Will Laurance
permalink: pretty
assets:
  js_compressor:  uglifier
  css_compressor: sass
sass:
  sass_dir: _includes/
  style: compressed

